
[package]
name = "rust-mux"
version = "0.1.0"
authors = ["Bryce Anderson <bryce.anderson22@gmail.com>"]

[dependencies]
byteorder = "0.4.2"
time = "0.1.34"
rand = "0.3.14"

[dependencies.mux]
path = "./lib/mux/"
